---
# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

rubocop:
  image: "ruby:2.7"
  script:
    - gem install rubocop -N
    - rubocop lib

test:
  before_script:
    - sed -e 's/# gem /gem /' -i Gemfile
    - gem install bundler -N
    - bundle install -j $(nproc) --path vendor
  image: "ruby:2.7"
  coverage: '/\((\d+(?:.\d+)?)\%\) covered/'
  script:
    - GENERATE_REPORTS=true CI_REPORTS=reports bundle exec rake test
  artifacts:
    expire_in: 1 week
    paths:
      - coverage/
    reports:
      junit: "reports/TEST-*.xml"
